apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx



# apiVersion tells Kubernetes how to interpret the YAML object, which schema to use, and which controller/API implementation should handle it.