apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: my-replicaset
  labels:
    app: backend
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:  
      app: backend