apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: my-replicaset
  labels:
    app: backend
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
  selector:
    matchLabels:  
      app: backend

# selector:
#   matchLabels:
#     app: backend                      # AND with the expressions below
#   matchExpressions:
#     - key: tier
#       operator: In
#       values: [web, api]              # tier=web OR tier=api
#     - key: env
#       operator: NotIn
#       values: [dev]                   # env must not be 'dev'
#     - key: canary
#       operator: DoesNotExist          # Pod must not have a 'canary' label
#     - key: version
#       operator: Exists                # Pod must have a 'version' label (any value)


# When the replication controller is created, it is not going to deploy a new instance of Pod if Pods with matching labels are already created.

# In that case, do we really need to provide a template session in the replica set specification?

# Since we are not expecting the replica set to create a new pod on deployment?

# Yes we do.

# Because in case one of the pods were to fail in the future, the replica set needs to create a new one to maintain the desired number of pods. And for the replica set to create a new pod, the template definition section is required.
